<form accept-charset="<?php echo $this->form->getAttrib('accept-charset'); ?>" id="<?php echo $this->form->getId();  ?>" name="<?php echo $this->form->getName(); ?>" enctype="<?php echo $this->form->getEnctype(); ?>" action="" method="<?php echo $this->form->getMethod(); ?>">
	<?php echo $this->form->idBike; ?>
	<label for="strBikeName" class="required"><?php echo $this->translate->_($this->form->strBikeName->getLabel()); ?></label><?php echo $this->form->strBikeName; ?><br />
	<?php echo $this->form->intBikeCategory; ?>
	<?php echo $this->form->submit; ?>
</form>