<ul>
<li><a href="<?php echo $this->url(array('controller' => 'categories')); ?>"><?php echo $this->translate->_('MOTOGP_TITLE_CATEGORIES'); ?></a></li>
<li><a href="<?php echo $this->url(array('controller' => 'bikes')); ?>"><?php echo $this->translate->_('MOTOGP_TITLE_BIKES'); ?></a></li>
<li><a href="<?php echo $this->url(array('controller' => 'teams')); ?>"><?php echo $this->translate->_('MOTOGP_TITLE_TEAMS'); ?></a></li>
<li><a href="<?php echo $this->url(array('controller' => 'riders')); ?>"><?php echo $this->translate->_('MOTOGP_TITLE_RIDERS'); ?></a></li>
<li><a href="<?php echo $this->url(array('controller' => 'races')); ?>"><?php echo $this->translate->_('MOTOGP_TITLE_RACES'); ?></a></li>
<li><a href="<?php echo $this->url(array('controller' => 'results')); ?>"><?php echo $this->translate->_('MOTOGP_TITLE_RESULTS'); ?></a></li>
</ul>