<form accept-charset="<?php echo $this->form->getAttrib('accept-charset'); ?>" id="<?php echo $this->form->getId();  ?>" name="<?php echo $this->form->getName(); ?>" enctype="<?php echo $this->form->getEnctype(); ?>" action="" method="<?php echo $this->form->getMethod(); ?>">
	<?php echo $this->form->idRider; ?>
	<?php echo $this->form->strRiderImage; ?>
	<label for="strRiderName" class="required"><?php echo $this->translate->_($this->form->strRiderName->getLabel()); ?></label><?php echo $this->form->strRiderName; ?><br />
	<?php echo $this->form->intRiderCategory; ?>	
	<?php echo $this->form->intRiderTeam; ?>	
	<?php echo $this->form->intRiderBike; ?>	
	<label for="intRiderNumber" class="required"><?php echo $this->translate->_($this->form->intRiderNumber->getLabel()); ?></label><?php echo $this->form->intRiderNumber; ?><br />
	<label for="dtRiderBirth" class="required"><?php echo $this->translate->_($this->form->dtRiderBirth->getLabel()); ?></label><?php echo $this->form->dtRiderBirth; ?><br />
	<label for="strRiderCity" class="required"><?php echo $this->translate->_($this->form->strRiderCity->getLabel()); ?></label><?php echo $this->form->strRiderCity; ?><br />
	<?php echo $this->form->intRiderCountry; ?>	
	<label for="intRiderWeight" class="required"><?php echo $this->translate->_($this->form->intRiderWeight->getLabel()); ?></label><?php echo $this->form->intRiderWeight; ?><br />
	<label for="intRiderHeight" class="required"><?php echo $this->translate->_($this->form->intRiderHeight->getLabel()); ?></label><?php echo $this->form->intRiderHeight; ?><br />
	<?php echo $this->form->strRiderImageFile; ?>
	<?php echo $this->form->submit; ?>
</form>
