<?php if ($this->msg) : ?>
<div><?php echo $this->msg; ?></div>
<?php endif; ?>
<a href="<?php echo $this->url(array('controller' => 'categories', 'action' => 'add'), null, true); ?>"><?php echo $this->translate->_('CATEGORIES_ADD_NEW'); ?></a>
<?php if (count($this->categorias) > 0) :?>
<table>
	<tr><td colspan="2"><?php echo $this->translate->_('CATEGORIES_TITLE'); ?></td></tr>
<?php
foreach($this->categorias AS $categoria){
?>
<tr>
	<td>
		<?php echo $categoria->strCategoryName; ?>
	</td>
	<td>
		<a href="<?php echo $this->url(array('controller'=>'categories','action'=>'edit','id'=>$categoria->idCategory), null, true);?>"><?php echo $this->translate->_('MOTOGP_EDIT'); ?></a>
		<a href="<?php echo $this->url(array('controller'=>'categories','action'=>'delete','id'=>$categoria->idCategory), null, true);?>"><?php echo $this->translate->_('MOTOGP_DELETE'); ?></a>
	</td>
</tr>
<?php
}
?>
</table>
<?php else :
?>
<div><?php echo $this->translate->_('CATEGORIES_ADD_NEW'); ?></div>
<?php 
endif; ?>