<form accept-charset="<?php echo $this->form->getAttrib('accept-charset'); ?>" id="<?php echo $this->form->getId();  ?>" name="<?php echo $this->form->getName(); ?>" enctype="<?php echo $this->form->getEnctype(); ?>" action="" method="<?php echo $this->form->getMethod(); ?>">
	<?php echo $this->form->idRace; ?>
	<label for="strRaceName" class="required"><?php echo $this->translate->_($this->form->strRaceName->getLabel()); ?></label><?php echo $this->form->strRaceName; ?><br />
	<?php echo $this->form->intRaceCategory; ?>
	<label for="dtRaceDate" class="required"><?php echo $this->translate->_($this->form->dtRaceDate->getLabel()); ?></label><?php echo $this->form->dtRaceDate; ?><br />
	<?php echo $this->form->intRaceCountry; ?>	
	<?php echo $this->form->submit; ?>
</form>